{defaultFirmwareLocation: 'C:/Mikrotik/routeros-mipsbe-6.42.6.npk', defaultIPListLocation: 'C:/Users/brich/Documents/GitHub/Revware/Revware_Mikrotik/ipList.txt',
  defaultNewPassword: '', defaultPassword: '', defaultTheme: DarkOrange.qss, defaultUsername: ''}
